language: go

go:
  - 1.8.3

before_script:
  - go get -u github.com/mitchellh/gox
  - go vet github.com/dropbox/dbxcli

install: true

script:
  - ./build.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "dist/*"
  file_glob: true
  on:
    tags: true
